# Railway deployment with PostgreSQL
[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'postgresql']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader'
]

[start]
cmd = 'php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'