# Railway deployment configuration
[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-scripts']

[start]
cmd = 'composer run-script post-autoload-dump && php artisan serve --host=0.0.0.0 --port=$PORT'